In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
x_train = pd.read_csv('../data/train_demographic_info.csv',
                    names=['patient_id', 'age', 'sex', 'adult_bmi', 'child_weight', 'child_height'])
x_train.head()

   patient_id    age sex  adult_bmi  child_weight  child_height
0           1  75.00   M       27.7           NaN           NaN
1           2   0.67   M        NaN           9.5          70.0
2           3  70.00   M       21.0           NaN           NaN
3           4   3.00   M        NaN          13.0          92.0
4           5  69.00   M       23.4           NaN           NaN

In [3]:
y_train = pd.read_csv('../data/train_patient_diagnosis.csv', names=['patient_id', 'diagnosis'])
y_train.head()

   patient_id      diagnosis
0           1           COPD
1           2  Bronchiolitis
2           3      Pneumonia
3           4  Bronchiolitis
4           5           COPD

In [4]:
train = pd.merge(x_train, y_train, how='inner', on='patient_id')
train.head()

   patient_id    age sex  adult_bmi  child_weight  child_height      diagnosis
0           1  75.00   M       27.7           NaN           NaN           COPD
1           2   0.67   M        NaN           9.5          70.0  Bronchiolitis
2           3  70.00   M       21.0           NaN           NaN      Pneumonia
3           4   3.00   M        NaN          13.0          92.0  Bronchiolitis
4           5  69.00   M       23.4           NaN           NaN           COPD

In [5]:
train.fillna('', inplace=True)
train.head()

   patient_id   age sex adult_bmi child_weight child_height      diagnosis
0           1    75   M      27.7                                     COPD
1           2  0.67   M                    9.5           70  Bronchiolitis
2           3    70   M        21                                Pneumonia
3           4     3   M                     13           92  Bronchiolitis
4           5    69   M      23.4                                     COPD

In [6]:
new_train = pd.DataFrame()
old_path = '../data/train'
new_path = '../data/input'
index = 0
file_prefix_set = set()
for file_name in os.listdir(old_path):
    patient_id = file_name.split('_')[0]
    file_prefix = file_name.split('.')[0]
    if file_prefix in file_prefix_set:
        continue
    else:
        file_prefix_set.add(file_prefix)
    new_path_dir = new_path + '/' + str(index)
    if not os.path.exists(new_path_dir):
        os.makedirs(new_path_dir)
#         print('{}/{}/{}'.format(old_path, dir_name, file_name))
#         print('{}/{}'.format(new_path_dir, file_name))
#     os.system("cp {}/{}.txt {}/{}.txt".format(old_path, file_prefix, new_path_dir, file_prefix))
#     os.system("cp {}/{}.wav {}/{}.wav".format(old_path, file_prefix, new_path_dir, file_prefix))
#         print(train[train['patient_id'] == int(patient_id)])
    new_train = new_train.append(train[train['patient_id'] == int(patient_id)], ignore_index=True)
    patient_id_index = list(new_train.columns).index('patient_id')
    new_train.iloc[index, patient_id_index] = index
#         print(new_train)
    index += 1

In [7]:
new_train.tail()

     patient_id age sex adult_bmi child_weight child_height diagnosis
764         764  58   F      24.7                                COPD
765         765  68   M      27.4                                COPD
766         766  63   M      16.5                                COPD
767         767  14   F                                       Healthy
768         768  75   M      27.7                                COPD

In [8]:
new_train['audio_and_txt_files_path'] = new_train['patient_id']
new_train.to_csv('../data/input/train.csv', index=None)

In [11]:
new_train['diagnosis'].value_counts()

COPD              655
Pneumonia          37
Healthy            29
Bronchiectasis     16
URTI               16
Bronchiolitis      13
LRTI                2
Asthma              1
Name: diagnosis, dtype: int64

In [ ]:
test = pd.read_csv('../data/test_demographic_info.csv',
                    names=['patient_id', 'age', 'sex', 'adult_bmi', 'child_weight', 'child_height'])
test.head()

In [ ]:
test.fillna('', inplace=True)
test.head()

In [ ]:
origin_index = 769
index = origin_index
new_test = pd.DataFrame()
old_path = '../data/test'
new_path = '../data/input'
file_prefix_set = set()
ids = []
for file_name in os.listdir(old_path):
    patient_id = file_name.split('_')[0]
    file_prefix = file_name.split('.')[0]
    if file_prefix in file_prefix_set:
        continue
    else:
        file_prefix_set.add(file_prefix)
    new_path_dir = new_path + '/' + str(index)
    if not os.path.exists(new_path_dir):
        os.makedirs(new_path_dir)
#     os.system("cp {}/{}.txt {}/{}.txt".format(old_path, file_prefix, new_path_dir, file_prefix))
#     os.system("cp {}/{}.wav {}/{}.wav".format(old_path, file_prefix, new_path_dir, file_prefix))
    new_test = new_test.append(test[test['patient_id'] == int(patient_id)], ignore_index=True)
    patient_id_index = list(new_test.columns).index('patient_id')
    new_test.iloc[index-origin_index, patient_id_index] = index
    ids.append(patient_id)
    index += 1

In [ ]:
new_test['id'] = ids
new_test.head()

In [ ]:
new_test['audio_and_txt_files_path'] = new_test['patient_id']
new_test.to_csv('../data/input/test.csv', index=None)